import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import crypto from 'node:crypto';
import dotenv from 'dotenv';
import {db,logActivity} from './db.js';
import {ref,token,hashToken,voucherCredential,normalizePhone,json,ghc} from './utils.js';
import {auth,admin,audit,optionalAuth} from './middleware/auth.js';
import {sendVoucherEmail,sendResetEmail} from './services/mailService.js';
import {provisionVoucher,disableVoucher,getUsage} from './services/hotspotService.js';
import {paystackInitialize,paystackVerify,verifyWebhook} from './services/paymentService.js';
dotenv.config();
const app=express();
app.set('trust proxy',1);app.use(helmet({crossOriginResourcePolicy:false}));app.use(cors({origin:true}));
const apiLimiter=rateLimit({windowMs:15*60*1000,max:300,standardHeaders:true,legacyHeaders:false});app.use('/api/',apiLimiter);
app.use(express.raw({type:'application/json',limit:'1mb',verify:(req,_,buf)=>{if(req.path==='/api/payments/webhook')req.rawBody=Buffer.from(buf)}}));
app.use((req,res,next)=>{if(req.path==='/api/payments/webhook')return next();try{if(Buffer.isBuffer(req.body))req.body=JSON.parse(req.body.toString()||'{}')}catch{return res.status(400).json({error:'Invalid JSON'})}next()});
const publicDir=new URL('../public/',import.meta.url).pathname;
app.use(express.static(publicDir));
app.get('/',(_,res)=>res.sendFile(publicDir+'connectnet-homepage.html'));
const emailRe=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const jwtSecret=process.env.JWT_SECRET;
function issue(u){return jwt.sign({sub:u.id,role:u.role},jwtSecret,{expiresIn:'7d'})}
function publicUser(u){return {id:u.id,name:u.name,email:u.email,phone:u.phone,role:u.role,status:u.status}}
function currentVoucher(userId){return db.prepare(`SELECT v.*,p.name package_name,p.data_bytes,p.duration_minutes,h.name hotspot_name FROM vouchers v JOIN packages p ON p.id=v.package_id JOIN hotspots h ON h.id=v.hotspot_id WHERE v.user_id=? AND v.status IN ('active','pending') ORDER BY v.created_at DESC LIMIT 1`).get(userId)}
async function activatePaidOrder(order){
 const existing=db.prepare('SELECT * FROM vouchers WHERE order_id=?').get(order.id); if(existing)return existing;
 const p=db.prepare('SELECT * FROM packages WHERE id=?').get(order.package_id); const h=db.prepare('SELECT * FROM hotspots WHERE id=?').get(order.hotspot_id); const u=db.prepare('SELECT * FROM users WHERE id=?').get(order.user_id);
 const username='CN'+voucherCredential(8), password=voucherCredential(10); const now=new Date(); const expires=p.duration_minutes?new Date(now.getTime()+p.duration_minutes*60000).toISOString():null;
 const info=db.prepare(`INSERT INTO vouchers(user_id,order_id,package_id,hotspot_id,username,password,status,data_limit_bytes,expires_at,activated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(u.id,order.id,p.id,h.id,username,password,'active',p.data_bytes,expires,now.toISOString());
 let v=db.prepare('SELECT * FROM vouchers WHERE id=?').get(info.lastInsertRowid);
 try{await provisionVoucher({...v,...p,...h,reference:order.reference});db.prepare('UPDATE vouchers SET router_sync_status="synced" WHERE id=?').run(v.id);}
 catch(e){db.prepare('UPDATE vouchers SET router_sync_status="failed",router_error=? WHERE id=?').run(String(e.message).slice(0,1000),v.id);logActivity({userId:u.id,action:'voucher.provision_failed',entityType:'voucher',entityId:v.id,details:{error:e.message}})}
 try{if(await sendVoucherEmail({to:u.email,name:u.name,username,password,packageName:p.name,dataLimit:formatBytes(p.data_bytes),expiresAt:expires,reference:order.reference}))db.prepare('UPDATE vouchers SET email_sent_at=CURRENT_TIMESTAMP WHERE id=?').run(v.id)}catch(e){logActivity({userId:u.id,action:'voucher.email_failed',entityType:'voucher',entityId:v.id,details:{error:e.message}})}
 logActivity({userId:u.id,action:'voucher.issued',entityType:'voucher',entityId:v.id,details:{order:order.reference,package:p.name}});return db.prepare('SELECT * FROM vouchers WHERE id=?').get(v.id);
}
function formatBytes(n){if(n>=1024**3)return `${(n/1024**3).toFixed(n%1024**3?2:0)} GB`;return `${Math.round(n/1024**2)} MB`}
async function markExhausted(v,reason){if(!v||v.status!=='active')return;try{await disableVoucher(v.username)}catch(e){}db.prepare(`UPDATE vouchers SET status='exhausted',exhausted_at=CURRENT_TIMESTAMP,disabled_at=CURRENT_TIMESTAMP,router_sync_status='synced' WHERE id=?`).run(v.id);logActivity({userId:v.user_id,action:'voucher.exhausted',entityType:'voucher',entityId:v.id,details:{reason}})}

app.get('/api/health',(req,res)=>res.json({ok:true,service:'connectnet',time:new Date().toISOString()}));
app.get('/api/status',(req,res)=>res.json({ok:true,database:!!db,hotspot:process.env.HOTSPOT_PROVIDER||'mock',payment:process.env.PAYMENT_PROVIDER||'paystack',time:new Date().toISOString()}));
app.get('/api/packages',(req,res)=>res.json(db.prepare('SELECT id,name,data_bytes,duration_minutes,price_pesewas,ROUND(price_pesewas/100.0,2) price_ghc FROM packages WHERE active=1 ORDER BY data_bytes').all()));
app.get('/api/hotspots',(req,res)=>res.json(db.prepare('SELECT id,name,location FROM hotspots WHERE active=1 ORDER BY name').all()));

app.post('/api/auth/register',async(req,res)=>{const {name,email,phone,password}=req.body||{};if(!name||name.trim().length<2||!emailRe.test(email||'')||!phone||String(password||'').length<8)return res.status(400).json({error:'Please provide a valid name, email, phone and password of at least 8 characters.'});const p=normalizePhone(phone);try{const hash=await bcrypt.hash(password,12);const r=db.prepare('INSERT INTO users(name,email,phone,password_hash) VALUES(?,?,?,?)').run(name.trim(),email.trim().toLowerCase(),p,hash);logActivity({userId:r.lastInsertRowid,action:'user.registered',entityType:'user',entityId:r.lastInsertRowid,ip:req.ip});res.status(201).json({ok:true,message:'Account created. Please login to continue purchasing.'})}catch(e){if(String(e.message).includes('UNIQUE'))return res.status(409).json({error:'An account with that email or phone already exists.'});res.status(500).json({error:'Registration failed'})}});
app.post('/api/auth/login',async(req,res)=>{const {email,password}=req.body||{};const u=db.prepare('SELECT * FROM users WHERE email=?').get(String(email||'').trim().toLowerCase());if(!u||!(await bcrypt.compare(password||'',u.password_hash)))return res.status(401).json({error:'Invalid email or password'});if(u.status!=='active')return res.status(403).json({error:'Your account is disabled. Contact support.'});db.prepare('UPDATE users SET last_login_at=CURRENT_TIMESTAMP,last_ip=? WHERE id=?').run(req.ip,u.id);logActivity({userId:u.id,actorRole:u.role,action:'auth.login',entityType:'user',entityId:u.id,ip:req.ip});res.json({token:issue(u),user:publicUser(u),redirect:u.role==='admin'?'/admin.htm':'/payment.htm'})});
app.get('/api/auth/me',auth,(req,res)=>res.json({user:req.user,voucher:currentVoucher(req.user.id)}));
app.post('/api/auth/forgot-password',async(req,res)=>{const contact=String(req.body?.contact||'').trim().toLowerCase();const u=db.prepare('SELECT * FROM users WHERE email=? OR phone=?').get(contact,contact);if(u){const raw=token();db.prepare('INSERT INTO password_resets(user_id,token_hash,expires_at) VALUES(?,?,?)').run(u.id,hashToken(raw),new Date(Date.now()+30*60000).toISOString());const url=`${process.env.APP_URL||'http://localhost:3000'}/reset-password.html?token=${raw}`;try{await sendResetEmail({to:u.email,name:u.name,resetUrl:url})}catch{}logActivity({userId:u.id,action:'auth.reset_requested',entityType:'user',entityId:u.id,ip:req.ip})}res.json({ok:true,message:'If the account exists, reset instructions have been sent.'})});
app.post('/api/auth/reset-password',async(req,res)=>{const {token:newToken,password}=req.body||{};if(!newToken||String(password||'').length<8)return res.status(400).json({error:'Invalid reset request'});const r=db.prepare(`SELECT pr.*,u.email FROM password_resets pr JOIN users u ON u.id=pr.user_id WHERE pr.token_hash=? AND pr.used_at IS NULL AND pr.expires_at>?`).get(hashToken(newToken),new Date().toISOString());if(!r)return res.status(400).json({error:'Reset link is invalid or expired'});db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(await bcrypt.hash(password,12),r.user_id);db.prepare('UPDATE password_resets SET used_at=CURRENT_TIMESTAMP WHERE id=?').run(r.id);logActivity({userId:r.user_id,action:'auth.password_reset',entityType:'user',entityId:r.user_id,ip:req.ip});res.json({ok:true})});

app.post('/api/payments/initialize',auth,async(req,res)=>{const {package_id,hotspot_id,payment_method='Mobile Money',momo_number}=req.body||{};const p=db.prepare('SELECT * FROM packages WHERE id=? AND active=1').get(Number(package_id));const h=db.prepare('SELECT * FROM hotspots WHERE id=? AND active=1').get(Number(hotspot_id));if(!p||!h)return res.status(400).json({error:'Select a valid package and hotspot'});const active=currentVoucher(req.user.id);if(active)return res.status(409).json({error:'You already have an active bundle. Use it until exhausted before buying another.',voucher:active});const reference=ref();db.prepare(`INSERT INTO orders(reference,user_id,package_id,hotspot_id,amount_pesewas,payment_method,payment_status,provider,metadata_json) VALUES(?,?,?,?,?,?,?,'paystack',?)`).run(reference,req.user.id,p.id,h.id,p.price_pesewas,payment_method,'pending',JSON.stringify({momo_number:momo_number||null}));const order=db.prepare('SELECT * FROM orders WHERE reference=?').get(reference);try{const data=await paystackInitialize({email:req.user.email,amount:p.price_pesewas,reference,metadata:{user_id:req.user.id,package_id:p.id,hotspot_id:h.id,order_id:order.id}});db.prepare('UPDATE orders SET provider_reference=? WHERE id=?').run(data.reference,order.id);logActivity({userId:req.user.id,action:'payment.initialized',entityType:'order',entityId:order.id,ip:req.ip,details:{reference,package:p.name}});res.json({ok:true,reference,authorization_url:data.authorization_url,access_code:data.access_code})}catch(e){db.prepare('UPDATE orders SET payment_status="failed" WHERE id=?').run(order.id);res.status(502).json({error:e.message})}});
app.get('/api/payments/:reference',auth,(req,res)=>{const o=db.prepare(`SELECT o.reference,o.amount_pesewas,o.payment_method,o.payment_status,o.created_at,o.paid_at,p.name package_name,h.name hotspot_name FROM orders o JOIN packages p ON p.id=o.package_id JOIN hotspots h ON h.id=o.hotspot_id WHERE o.reference=? AND o.user_id=?`).get(req.params.reference,req.user.id);if(!o)return res.status(404).json({error:'Order not found'});const v=db.prepare('SELECT id,username,password,status,data_limit_bytes,data_used_bytes,expires_at,email_sent_at FROM vouchers WHERE order_id=(SELECT id FROM orders WHERE reference=?)').get(req.params.reference);res.json({order:o,voucher:v})});
async function verifyAndFulfill(reference){const o=db.prepare('SELECT * FROM orders WHERE reference=?').get(reference);if(!o)throw new Error('Order not found');if(o.payment_status==='paid')return activatePaidOrder(o);const d=await paystackVerify(reference);if(d.status!=='success')return null;db.prepare(`UPDATE orders SET payment_status='paid',paid_at=CURRENT_TIMESTAMP,provider_reference=? WHERE id=?`).run(d.reference,o.id);logActivity({userId:o.user_id,action:'payment.confirmed',entityType:'order',entityId:o.id,details:{reference}});return activatePaidOrder(db.prepare('SELECT * FROM orders WHERE id=?').get(o.id));}
app.post('/api/payments/verify',auth,async(req,res)=>{try{const v=await verifyAndFulfill(req.body?.reference);if(!v)return res.status(202).json({ok:false,status:'pending'});res.json({ok:true,voucher:{username:v.username,password:v.password,status:v.status,data_limit_bytes:v.data_limit_bytes,expires_at:v.expires_at}})}catch(e){res.status(502).json({error:e.message})}});
app.post('/api/payments/webhook',(req,res)=>{const sig=req.headers['x-paystack-signature'];if(!verifyWebhook(req.rawBody||Buffer.from(''),sig||''))return res.status(401).send('invalid signature');res.sendStatus(200);setImmediate(async()=>{try{const event=JSON.parse(req.rawBody.toString());if(event.event==='charge.success')await verifyAndFulfill(event.data.reference)}catch(e){console.error('Webhook fulfillment error',e)}})});

app.get('/api/me/vouchers',auth,(req,res)=>res.json(db.prepare(`SELECT v.id,v.username,v.password,v.status,v.data_limit_bytes,v.data_used_bytes,v.expires_at,v.created_at,p.name package_name,h.name hotspot_name,o.reference FROM vouchers v JOIN packages p ON p.id=v.package_id JOIN hotspots h ON h.id=v.hotspot_id JOIN orders o ON o.id=v.order_id WHERE v.user_id=? ORDER BY v.created_at DESC`).all(req.user.id)));
app.post('/api/vouchers/validate',async(req,res)=>{const {username,password}=req.body||{};const v=db.prepare('SELECT v.*,p.name package_name FROM vouchers v JOIN packages p ON p.id=v.package_id WHERE v.username=?').get(username);if(!v||v.password!==password)return res.status(401).json({valid:false});if(v.status!=='active'||(v.expires_at&&new Date(v.expires_at)<new Date())){if(v.status==='active')await markExhausted(v,'expired');return res.json({valid:false,reason:'expired_or_exhausted'})}res.json({valid:true,package:v.package_name,remaining_bytes:Math.max(0,v.data_limit_bytes-v.data_used_bytes),expires_at:v.expires_at})});

app.post('/api/support/tickets',optionalAuth,(req,res)=>{const b=req.body||{};if(!b.message||String(b.message).length<5)return res.status(400).json({error:'Please describe your issue'});const r=db.prepare(`INSERT INTO support_tickets(user_id,name,phone,email,issue,location,reference,message) VALUES(?,?,?,?,?,?,?,?)`).run(req.user?.id||null,b.name||req.user?.name||'Customer',b.phone||req.user?.phone||'',b.email||req.user?.email||'',b.issue||'',b.location||'',b.reference||'',b.message);logActivity({userId:req.user?.id||null,action:'support.created',entityType:'ticket',entityId:r.lastInsertRowid,ip:req.ip});res.status(201).json({ok:true,id:r.lastInsertRowid})});

app.get('/api/me/dashboard',auth,(req,res)=>{const stats=db.prepare(`SELECT COUNT(*) orders,COALESCE(SUM(CASE WHEN payment_status='paid' THEN amount_pesewas ELSE 0 END),0) spent FROM orders WHERE user_id=?`).get(req.user.id);res.json({user:req.user,stats,vouchers:db.prepare(`SELECT v.*,p.name package_name FROM vouchers v JOIN packages p ON p.id=v.package_id WHERE v.user_id=? ORDER BY v.created_at DESC`).all(req.user.id)})});

app.use('/api/admin',auth,admin);
app.get('/api/admin/dashboard',(req,res)=>{const counts={users:db.prepare("SELECT COUNT(*) c FROM users WHERE role='customer'").get().c,orders:db.prepare('SELECT COUNT(*) c FROM orders').get().c,paid:db.prepare("SELECT COUNT(*) c FROM orders WHERE payment_status='paid'").get().c,vouchers:db.prepare('SELECT COUNT(*) c FROM vouchers').get().c,active_vouchers:db.prepare("SELECT COUNT(*) c FROM vouchers WHERE status='active'").get().c,support_open:db.prepare("SELECT COUNT(*) c FROM support_tickets WHERE status IN ('open','pending')").get().c,revenue_pesewas:db.prepare("SELECT COALESCE(SUM(amount_pesewas),0) s FROM orders WHERE payment_status='paid'").get().s};res.json({counts,recentOrders:db.prepare(`SELECT o.reference,u.name customer,u.email,p.name package_name,o.amount_pesewas,o.payment_status,o.created_at FROM orders o JOIN users u ON u.id=o.user_id JOIN packages p ON p.id=o.package_id ORDER BY o.created_at DESC LIMIT 12`).all()})});
app.get('/api/admin/users',(req,res)=>res.json(db.prepare(`SELECT u.id,u.name,u.email,u.phone,u.status,u.created_at,u.last_login_at,COUNT(o.id) orders,COALESCE(SUM(CASE WHEN o.payment_status='paid' THEN o.amount_pesewas ELSE 0 END),0) spent FROM users u LEFT JOIN orders o ON o.user_id=u.id WHERE u.role='customer' GROUP BY u.id ORDER BY u.created_at DESC`).all()));
app.patch('/api/admin/users/:id/status',(req,res)=>{const s=req.body?.status;if(!['active','disabled'].includes(s))return res.status(400).json({error:'Invalid status'});db.prepare('UPDATE users SET status=? WHERE id=? AND role="customer"').run(s,Number(req.params.id));audit(req,`user.${s}`, 'user',Number(req.params.id));res.json({ok:true})});
app.get('/api/admin/orders',(req,res)=>res.json(db.prepare(`SELECT o.*,u.name customer,u.email,u.phone,p.name package_name,h.name hotspot_name FROM orders o JOIN users u ON u.id=o.user_id JOIN packages p ON p.id=o.package_id JOIN hotspots h ON h.id=o.hotspot_id ORDER BY o.created_at DESC`).all()));
app.get('/api/admin/vouchers',(req,res)=>res.json(db.prepare(`SELECT v.*,u.name customer,u.email,p.name package_name,h.name hotspot_name,o.reference FROM vouchers v JOIN users u ON u.id=v.user_id JOIN packages p ON p.id=v.package_id JOIN hotspots h ON h.id=v.hotspot_id JOIN orders o ON o.id=v.order_id ORDER BY v.created_at DESC`).all()));
app.patch('/api/admin/vouchers/:id/status',async(req,res)=>{const s=req.body?.status;if(!['active','disabled','exhausted'].includes(s))return res.status(400).json({error:'Invalid status'});const v=db.prepare('SELECT * FROM vouchers WHERE id=?').get(Number(req.params.id));if(!v)return res.status(404).json({error:'Voucher not found'});if(s!=='active')try{await disableVoucher(v.username)}catch{}db.prepare('UPDATE vouchers SET status=?,disabled_at=CASE WHEN ?<>"active" THEN CURRENT_TIMESTAMP ELSE NULL END WHERE id=?').run(s,s,v.id);audit(req,`voucher.${s}`,'voucher',v.id);res.json({ok:true})});
app.delete('/api/admin/vouchers/:id',async(req,res)=>{const v=db.prepare('SELECT * FROM vouchers WHERE id=?').get(Number(req.params.id));if(!v)return res.status(404).json({error:'Not found'});try{await disableVoucher(v.username)}catch{}db.prepare('DELETE FROM vouchers WHERE id=?').run(v.id);audit(req,'voucher.deleted','voucher',v.id);res.json({ok:true})});
app.get('/api/admin/packages',(req,res)=>res.json(db.prepare('SELECT *,ROUND(price_pesewas/100.0,2) price_ghc FROM packages ORDER BY data_bytes').all()));
app.post('/api/admin/packages',(req,res)=>{const b=req.body||{};if(!b.name||!b.data_gb||!b.price_ghc)return res.status(400).json({error:'name, data_gb and price_ghc are required'});const r=db.prepare('INSERT INTO packages(name,data_bytes,duration_minutes,price_pesewas,active) VALUES(?,?,?,?,?)').run(b.name,Math.round(Number(b.data_gb)*1024**3),Number(b.duration_minutes||0),Math.round(Number(b.price_ghc)*100),b.active===false?0:1);audit(req,'package.created','package',r.lastInsertRowid);res.status(201).json({id:r.lastInsertRowid})});
app.patch('/api/admin/packages/:id',(req,res)=>{const b=req.body||{};const old=db.prepare('SELECT * FROM packages WHERE id=?').get(Number(req.params.id));if(!old)return res.status(404).json({error:'Not found'});db.prepare('UPDATE packages SET name=?,data_bytes=?,duration_minutes=?,price_pesewas=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(b.name??old.name, b.data_gb!=null?Math.round(Number(b.data_gb)*1024**3):old.data_bytes,b.duration_minutes??old.duration_minutes,b.price_ghc!=null?Math.round(Number(b.price_ghc)*100):old.price_pesewas,b.active==null?old.active:b.active?1:0,old.id);audit(req,'package.updated','package',old.id);res.json({ok:true})});
app.get('/api/admin/hotspots',(req,res)=>res.json(db.prepare('SELECT * FROM hotspots ORDER BY created_at DESC').all()));
app.post('/api/admin/hotspots',(req,res)=>{const b=req.body||{};const r=db.prepare('INSERT INTO hotspots(name,location,router_url,provider,profile,active) VALUES(?,?,?,?,?,?)').run(b.name,b.location,b.router_url||'',b.provider||'mock',b.profile||'default',b.active===false?0:1);audit(req,'hotspot.created','hotspot',r.lastInsertRowid);res.status(201).json({id:r.lastInsertRowid})});
app.patch('/api/admin/hotspots/:id',(req,res)=>{const h=db.prepare('SELECT * FROM hotspots WHERE id=?').get(Number(req.params.id));if(!h)return res.status(404).json({error:'Not found'});const b=req.body||{};db.prepare('UPDATE hotspots SET name=?,location=?,router_url=?,provider=?,profile=?,active=? WHERE id=?').run(b.name??h.name,b.location??h.location,b.router_url??h.router_url,b.provider??h.provider,b.profile??h.profile,b.active==null?h.active:b.active?1:0,h.id);audit(req,'hotspot.updated','hotspot',h.id);res.json({ok:true})});
app.get('/api/admin/support',(req,res)=>res.json(db.prepare(`SELECT s.*,u.name account_name FROM support_tickets s LEFT JOIN users u ON u.id=s.user_id ORDER BY s.created_at DESC`).all()));
app.patch('/api/admin/support/:id',(req,res)=>{const b=req.body||{};db.prepare('UPDATE support_tickets SET status=?,admin_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(b.status||'pending',b.admin_note||'',Number(req.params.id));audit(req,'support.updated','ticket',Number(req.params.id));res.json({ok:true})});
app.get('/api/admin/activity',(req,res)=>res.json(db.prepare(`SELECT a.*,u.name user_name,u.email user_email FROM activity_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 500`).all().map(x=>({...x,details:json(x.details_json)}))));
app.get('/api/admin/settings',(req,res)=>res.json({payment_provider:process.env.PAYMENT_PROVIDER||'paystack',hotspot_provider:process.env.HOTSPOT_PROVIDER||'mock',smtp_configured:!!process.env.SMTP_HOST,app_url:process.env.APP_URL||''}));

setInterval(async()=>{const active=db.prepare(`SELECT v.*,p.duration_minutes FROM vouchers v JOIN packages p ON p.id=v.package_id WHERE v.status='active'`).all();for(const v of active){if(v.expires_at&&new Date(v.expires_at)<=new Date()){await markExhausted(v,'time_limit');continue}try{const usage=await getUsage(v.username);if(usage?.bytes!=null){db.prepare('UPDATE vouchers SET data_used_bytes=? WHERE id=?').run(usage.bytes,v.id);if(usage.bytes>=v.data_limit_bytes)await markExhausted({...v,data_used_bytes:usage.bytes},'data_limit')}}catch(e){}}},30000);

app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Internal server error'})});
const port=Number(process.env.PORT||3000);app.listen(port,()=>console.log(`ConnectNet running on ${process.env.APP_URL||`http://localhost:${port}`}`));
